### ISSUE TITLE
Crash, if package have more then 56 points

### ISSUE THREAD

**Issue by d-martynov** [rogerdahl/striprouter#1]
Application crash, if one of packages have more than 56 points.

Example .circuit:

> board 25,25
> P 1,0 2,0 3,0 4,0 5,0 6,0 7,0 8,0 1,1 2,1 3,1 4,1 5,1 6,1 7,1 8,1 0,2 1,2 13,2 0,3 1,3 12,3 13,3 0,4 1,4 12,4 13,4 0,5 1,5 12,5 13,5 0,6 1,6 12,6 13,6 0,7 1,7 12,7 13,7 0,8 1,8 12,8 13,8 0,9 1,9 12,9 13,9 12,10 1,14 1,15 2,15 3,15 4,15 5,15 6,15 7,15 1,16
> P1 P 0,0

System:
Windows 10 Pro x64

**Comment by rogerdahl** [comment]
Thanks for trying out the app. I hope to release a new version with a fix for this within a few hours.

**Comment by rogerdahl** [comment]
We were running into some limitations of `std:regex` in VS. I've added a 1.0.1 release that should stress the regex engine less. Please open a new issue if it doesn't work for you.
