### ISSUE TITLE
Downloaded 1.0.1 Windows 10 64 Bit does not run , please help

### ISSUE THREAD

**Issue by plug-it-in** [rogerdahl/striprouter#2]
Hi I have downloaded the binary zip , unpacked it and run striprouter from the command line and from explorer and nothing happens.

Am I supposed to regeister the  glew.dll or do anything else ?

No errors and no messages.  Would appreciate any help or direction

**Comment by rogerdahl** [comment]
I tried it now, and the 1.0.1 version doesn't work for me either, on current Windows 10. However, version 1.0.0 works for me. I've deleted the 1.0.1 version for now. Let me know if you have trouble with 1.0.0.
